name: jellybean
description: "Yet another jellyfin client"

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.4.0-190.1.beta <4.0.0'

# To automatically upgrade your package dependencies to the latest versions
# flutter pub upgrade --major-versions

# To see which dependencies have newer
# flutter pub outdated
dependencies:
  flutter:
    sdk: flutter

  # utils
  logger: ^2.3.0
  path_provider: ^2.1.3
  universal_html: ^2.2.4
  package_info_plus: ^8.0.0
  device_info_plus: ^10.1.0
  url_launcher: ^6.2.6

  # db
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.21
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3
  # router
  go_router: ^14.1.2
  # state management
  flutter_riverpod: ^2.5.1
  get_it: ^7.7.0

  # UI stuff
  cached_network_image: ^3.3.1
  flutter_animate: ^4.5.0

  # jellyfin sdk
  jellydart:
    git:
      url: https://github.com/RA341/jellydart.git
      ref: main
      path: jellydart

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.18.0
  json_serializable: ^6.8.0
  build_runner: any
  flutter_lints: ^4.0.0
  custom_lint:
  riverpod_lint:
  very_good_analysis: ^5.1.0
  msix: ^3.16.7

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700


msix_config:
  display_name: Jellybean
  publisher_display_name: Dumbapps
  identity_name: app.dumb.jellybean
  capabilities: internetClient
#  logo_path: C:\path\to\logo.png
